package net.allthemods.alltheores.core.registry;

import net.minecraft.tags.BlockTags;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;

import net.allthemods.alltheores.common.material.Material;
import net.allthemods.alltheores.common.parts.BlockPartType;
import net.allthemods.alltheores.common.parts.ItemPartType;

// TODO: Add .add(BlockPartType.ANCHIENT_ORE) where applicable once ATM updates to 26.1
public final class Materials {
    
    public static void init() { }
    
    public static final Material ALUMINUM = Material.builder("aluminum", BlockTags.NEEDS_STONE_TOOL)
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.RAW)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.RAW_BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(24, 4, -64, 320)
            .build();
    
    public static final Material LEAD = Material.builder("lead", BlockTags.NEEDS_STONE_TOOL)
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.RAW)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.RAW_BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(24, 3, -64, 56)
            .build();
    
    public static final Material NICKEL = Material.builder("nickel", BlockTags.NEEDS_IRON_TOOL)
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.RAW)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.RAW_BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(24, 3, -64, 56)
            .build();
    
    public static final Material OSMIUM = Material.builder("osmium", BlockTags.NEEDS_DIAMOND_TOOL)
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.RAW)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.RAW_BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(24, 3, -64, 56)
            .build();
    
    public static final Material PLATINUM = Material.builder("platinum", BlockTags.NEEDS_DIAMOND_TOOL)
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.RAW)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.RAW_BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(24, 1, -64, 36)
            .build();
    
    public static final Material SILVER = Material.builder("silver", BlockTags.NEEDS_STONE_TOOL)
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.RAW)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.RAW_BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(24, 3, -64, 56)
            .build();
    
    public static final Material TIN = Material.builder("tin", BlockTags.NEEDS_STONE_TOOL)
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.RAW)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.RAW_BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(24, 4, -64, 196)
            .build();
    
    public static final Material URANIUM = Material.builder("uranium", BlockTags.NEEDS_IRON_TOOL)
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.RAW)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.RAW_BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(24, 2, -64, 16)
            .build();
    
    public static final Material ZINC = Material.builder("zinc", BlockTags.NEEDS_STONE_TOOL)
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.RAW)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.RAW_BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(24, 3, -64, 126)
            .build();
    
    public static final Material IRIDIUM = Material.builder("iridium", BlockTags.NEEDS_DIAMOND_TOOL)
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.RAW)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.RAW_BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(10, 4, -64, 32)
            .build();
    
    public static final Material STEEL = Material.builder("steel")
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .build();
    
    public static final Material INVAR = Material.builder("invar")
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .build();
    
    public static final Material ELECTRUM = Material.builder("electrum")
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .build();
    
    public static final Material BRONZE = Material.builder("bronze")
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .build();
    
    public static final Material BRASS = Material.builder("brass")
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .build();
    
    public static final Material ENDERIUM = Material.builder("enderium")
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .build();
    
    public static final Material LUMIUM = Material.builder("lumium")
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .build();
    
    public static final Material SIGNALUM = Material.builder("signalum")
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .build();
    
    public static final Material CONSTANTAN = Material.builder("constantan")
            .add(ItemPartType.NUGGET)
            .add(ItemPartType.INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK)
            .build();
    
    public static final Material RUBY = Material.builder("ruby", BlockTags.NEEDS_STONE_TOOL)
            .add(ItemPartType.GEM)
            .add(ItemPartType.DUST)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(7, 3, -64, 228)
            .build();
    
    public static final Material PERIDOT = Material.builder("peridot", BlockTags.NEEDS_STONE_TOOL)
            .add(ItemPartType.GEM)
            .add(ItemPartType.DUST)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(7, 3, -64, 196)
            .build();
    
    public static final Material SAPPHIRE = Material.builder("sapphire", BlockTags.NEEDS_STONE_TOOL)
            .add(ItemPartType.GEM)
            .add(ItemPartType.DUST)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(7, 3, -64, 296)
            .build();
    
    public static final Material CINNABAR = Material.builder("cinnabar", BlockTags.NEEDS_IRON_TOOL)
            .add(ItemPartType.GEM)
            .add(ItemPartType.DUST)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(27, 3, -64, 228)
            .build();
    
    public static final Material FLUORITE = Material.builder("fluorite", BlockTags.NEEDS_IRON_TOOL)
            .add(ItemPartType.GEM)
            .add(ItemPartType.DUST)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(27, 3, -64, 228)
            .build();
    
    public static final Material SALT = Material.builder("salt", BlockTags.NEEDS_STONE_TOOL)
            .add(ItemPartType.DUST)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(27, 3, -64, 228)
            .build();
    
    public static final Material SULFUR = Material.builder("sulfur", BlockTags.NEEDS_IRON_TOOL)
            .add(ItemPartType.DUST)
            .add(BlockPartType.BLOCK)
            .add(BlockPartType.STONE_ORE)
            .add(BlockPartType.DEEPSLATE_ORE)
            .add(BlockPartType.NETHER_ORE)
            .add(BlockPartType.END_ORE)
            .worldgen(17, 1, -64, 25)
            .build();
    
    public static final Material COPPER = Material.builder("copper")
            .add(ItemPartType.NUGGET, Items.COPPER_NUGGET)
            .add(ItemPartType.RAW, Items.RAW_COPPER)
            .add(ItemPartType.INGOT, Items.COPPER_INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK, Blocks.COPPER_BLOCK)
            .add(BlockPartType.RAW_BLOCK, Blocks.RAW_COPPER_BLOCK)
            .add(BlockPartType.STONE_ORE, Blocks.COPPER_ORE)
            .add(BlockPartType.DEEPSLATE_ORE, Blocks.DEEPSLATE_COPPER_ORE)
            .build();
    
    public static final Material IRON = Material.builder("iron")
            .add(ItemPartType.NUGGET, Items.IRON_NUGGET)
            .add(ItemPartType.RAW, Items.RAW_IRON)
            .add(ItemPartType.INGOT, Items.IRON_INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK, Blocks.IRON_BLOCK)
            .add(BlockPartType.RAW_BLOCK, Blocks.RAW_IRON_BLOCK)
            .add(BlockPartType.STONE_ORE, Blocks.IRON_ORE)
            .add(BlockPartType.DEEPSLATE_ORE, Blocks.DEEPSLATE_IRON_ORE)
            .build();
    
    public static final Material GOLD = Material.builder("gold")
            .add(ItemPartType.NUGGET, Items.GOLD_NUGGET)
            .add(ItemPartType.RAW, Items.RAW_GOLD)
            .add(ItemPartType.INGOT, Items.GOLD_INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK, Blocks.GOLD_BLOCK)
            .add(BlockPartType.RAW_BLOCK, Blocks.RAW_GOLD_BLOCK)
            .add(BlockPartType.STONE_ORE, Blocks.GOLD_ORE)
            .add(BlockPartType.DEEPSLATE_ORE, Blocks.DEEPSLATE_GOLD_ORE)
            .add(BlockPartType.NETHER_ORE, Blocks.NETHER_GOLD_ORE)
            .build();
    
    public static final Material DIAMOND = Material.builder("diamond")
            .add(ItemPartType.GEM, Items.DIAMOND)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK, Blocks.DIAMOND_BLOCK)
            .add(BlockPartType.STONE_ORE, Blocks.DIAMOND_ORE)
            .add(BlockPartType.DEEPSLATE_ORE, Blocks.DEEPSLATE_DIAMOND_ORE)
            .build();
    
    public static final Material NETHERITE = Material.builder("netherite")
            .add(ItemPartType.INGOT, Items.NETHERITE_INGOT)
            .add(ItemPartType.DUST)
            .add(ItemPartType.GEAR)
            .add(ItemPartType.PLATE)
            .add(ItemPartType.ROD)
            .add(BlockPartType.BLOCK, Blocks.NETHERITE_BLOCK)
            .build();
}
